CREATE schema RelDB
Use RelDB;
CREATE TABLE superstore1 
(ROWID INTEGER NOT NULL,
ORDERID VARCHAR(32),
ORDERDATE DATE NOT NULL,
SHIPDATE DATE NOT NULL,
SHIPMODE VARCHAR(32) NOT NULL,
CUSTOMERID VARCHAR(32) NOT NULL,
CUSTOMERNAME VARCHAR(50) NOT NULL,
SEGMENT VARCHAR(32) NOT NULL,
COUNTRY VARCHAR(16) NOT NULL,
CITY VARCHAR(16) NOT NULL,
STATE VARCHAR(16) NOT NULL,
POSTALCODE INTEGER NOT NULL,
REGION VARCHAR(16) NOT NULL,
PRODUCTID VARCHAR(32) NOT NULL,
CATEGORY VARCHAR(32) NOT NULL,
SUBCATEGORY VARCHAR(32) NOT NULL,
PRODUCTNAME VARCHAR(32) NOT NULL,
SALES VARCHAR(32) NOT NULL,
QUANTITY INTEGER NOT NULL,
DISCOUNT VARCHAR(32) NOT NULL,
PROFIT VARCHAR(32) NOT NULL, PRIMARY KEY(ROWID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET GLOBAL local_infile = ON
LOAD DATA LOCAL INFILE '/Users/MAdamAnees/Desktop/DataEng1/Superstore1.csv'
INTO TABLE Superstore1
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(ROWID, ORDERID, ORDERDATE, SHIPDATE, SHIPMODE, CUSTOMERID, CUSTOMERNAME, SEGMENT, COUNTRY, CITY, STATE, POSTALCODE, REGION, PRODUCTID, CATEGORY, SUBCATEGORY, PRODUCTNAME, SALES, QUANTITY, DISCOUNT, PROFIT)
;
SET GLOBAL local_infile=1;
SHOW GLOBAL VARIABLES LIKE 'local_infile';
quit
use Reldb
DROP TABLE IF EXISTS superstore1;
SELECT * from superstore1 LIMIT 1500,1
DROP TABLE IF EXISTS superstore3
CREATE TABLE superstore2
(RETURNED VARCHAR(32) NOT NULL,
ORDERID VARCHAR(32) NOT NULL, PRIMARY KEY(ORDERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
LOAD DATA LOCAL INFILE '/Users/MAdamAnees/Desktop/DataEng1/Superstore2.csv'
INTO TABLE Superstore2
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(RETURNED, ORDERID)
;
CREATE TABLE superstore3
(PERSON VARCHAR(32) NOT NULL,
REGION VARCHAR(32) NOT NULL, PRIMARY KEY(REGION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
LOAD DATA LOCAL INFILE '/Users/MAdamAnees/Desktop/DataEng1/Superstore3.csv'
INTO TABLE Superstore3
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(PERSON, REGION)
;


